### ISSUE TITLE
useKeyboard on Android

### ISSUE THREAD

**Issue by andreasbergqvist** [react-native-community/react-native-hooks#17]
keyboardWillShow & keyboardWillHide is not available on Android.
See: https://facebook.github.io/react-native/docs/keyboard

One idea is to listen to those + keyboardDidShow & keyboardDidHide (these are available on Android).

Would that be a feasible solution or will it mess something up?

**Comment by nmantulenko** [comment]
react-navigation-tabs uses the next technique
`componentDidMount() {
    if (Platform.OS === 'ios') {
      Keyboard.addListener('keyboardWillShow', this._handleKeyboardShow);
      Keyboard.addListener('keyboardWillHide', this._handleKeyboardHide);
    } else {
      Keyboard.addListener('keyboardDidShow', this._handleKeyboardShow);
      Keyboard.addListener('keyboardDidHide', this._handleKeyboardHide);
    }
  }

  componentWillUnmount() {
    if (Platform.OS === 'ios') {
      Keyboard.removeListener('keyboardWillShow', this._handleKeyboardShow);
      Keyboard.removeListener('keyboardWillHide', this._handleKeyboardHide);
    } else {
      Keyboard.removeListener('keyboardDidShow', this._handleKeyboardShow);
      Keyboard.removeListener('keyboardDidHide', this._handleKeyboardHide);
    }
  }

  _handleKeyboardShow = () =>
    this.setState({ keyboard: true }, () =>
      Animated.timing(this.state.visible, {
        toValue: 0,
        duration: 150,
        useNativeDriver: true,
      }).start()
    );

  _handleKeyboardHide = () =>
    Animated.timing(this.state.visible, {
      toValue: 1,
      duration: 100,
      useNativeDriver: true,
    }).start(() => {
      this.setState({ keyboard: false });
    });`

btw
`this.keyboardWillShowListener` - this -> global context

**Comment by HarshaKoshila** [comment]
Note that if you set android:windowSoftInputMode to adjustResize or adjustPan, only keyboardDidShow and keyboardDidHide events will be available on Android. If you set android:windowSoftInputMode to adjustNothing, no events will be available on Android. 


Change  **adjustNothing** from your **AndroidManifest file**
