### ISSUE TITLE
Deprecated APIs

### ISSUE THREAD

**Issue by mifi** [react-native-community/react-native-hooks#18]
Many APIs are now deprecated by facebook.

See for example:
https://facebook.github.io/react-native/docs/netinfo

How should we handle this? peerDependencies?

**Comment by guhungry** [comment]
For netinfo, there are [issue](https://github.com/react-native-community/react-native-netinfo/issues/29) for that. So netinfo related hooks should be removed.

**Comment by pvinis** [comment]
We have no netinfo related hooks anymore, so we can close this. Thanks!
