### ISSUE TITLE
useKeyboard hook clarifications

### ISSUE THREAD

**Issue by natasha08n** [react-native-community/react-native-hooks#44]
# Is it correct that you bind `keyboardHidden` method to `keyboardWillShow` event?

https://github.com/react-native-community/react-native-hooks/blob/7abd32f513db2cc5ecedb504cb50827685ae6d7b/lib/useKeyboard.js#L26-L28

**Comment by breadadams** [comment]
This looks to be addressed in #39 #37 and #41 - hopefully one will be merged soon 😅

**Comment by LinusU** [comment]
This should be fixed in the newly released `@react-native-community/hooks` 2.0.0, just verified myself in the published package 🚀
