### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by heroandtn3** [react-native-community/react-native-hooks#49]
Excuse me for the words but I just looked around the hooks and saw so many bad practices in your project (mostly about performance) so I wonder whether you still maintain this project or not.

For example, this hook does resubscribe event every time the component renders. There is a fix here but for maybe some reasons it is merged yet: https://github.com/react-native-community/react-native-hooks/pull/38

`src/useAppState.ts`

```javascript

import React, { useEffect, useState } from 'react'
import { AppState, AppStateStatus } from 'react-native'

export default function useAppState() {
  const currentState = AppState.currentState
  const [appState, setAppState] = useState(currentState)

  function onChange(newState: AppStateStatus) {
    setAppState(newState)
  }

  useEffect(() => {
    AppState.addEventListener('change', onChange)

    return () => {
      AppState.removeEventListener('change', onChange)
    }
  })

  return appState
}
```

This hook creates new `getPhotos` and `saveToCameraRoll` functions every time the hook is called. It would cause the hook consumer component to rerender unexpectedly.

`src/useCameraRoll.ts`

```javascript
export default function useCameraRoll() {
  const [photos, setPhotos] = useState(initialState)

  async function getPhotos(config = defaultConfig) {
    try {
      const photos = await CameraRoll.getPhotos(config)
      setPhotos(photos)
    } catch (err) {
      console.log('error: ', err)
    }
  }

  async function saveToCameraRoll(tag: string, type?: 'photo' | 'video') {
    try {
      await CameraRoll.saveToCameraRoll(tag, type)
    } catch (err) {
      console.log('error saving to camera roll: ', err)
    }
  }

  return [photos, getPhotos, saveToCameraRoll]
}
```

**Comment by LinusU** [comment]
@pvinis It seems like version 1.0.0 isn't published to npm, and there are also more commits since 1.0.0 that would be great if we could get released!

There is also a lot of open issues that seems like we could close after cutting a new release, and still a few pull requests that could either be closed, or updated and merged.

If you want someone to help maintain this library I would be happy to step up! As it stands right now we are a bit hesitant to depend on this library 😅 

Thanks!

**Comment by pvinis** [comment]
Right, I'm with you! I don't actually have permission to publish. Let's ping @kelset about how to handle this.

**Comment by kelset** [comment]
Hey folks 👋 sorry, I've forgot to update here. I've raised this in the Discord and AFAIK we are reaching out to the original developer to get some auths. This should unlock this lib and we'll get a couple maintainers (if I understood the conversation 😅)

**Comment by pvinis** [comment]
Ongoing :)

**Comment by DragonRaider5** [comment]
+1

**Comment by pvinis** [comment]
It's out people! https://www.npmjs.com/package/@react-native-community/hooks

Install with `yarn add @react-native-community/hooks`!
