### ISSUE TITLE
Remove useDimensions?

### ISSUE THREAD

**Issue by Naturalclar** [react-native-community/react-native-hooks#54]
# Question

From React Native v0.61, `useWindowDimensions` has been implemented to the core repository https://github.com/facebook/react-native/commit/5ec382d#diff-d22b00f3f4e10cfb3e6ac4e653bcebd7R17

This is essentially the same functionality as `useDimensions` in this repo.
Should `useDimensions` be removed from this package? or should it continue to exist for RN 0.59, and 0.60 users?

**Comment by pvinis** [comment]
I would say let's keep it still. Since 0.61 is the current latest stable, we are fine keeping it, and maybe later we can deprecate and/or remove it.

I'll close this, but everyone feel free to comment if you feel strongly one way or the other.
