### ISSUE TITLE
Can't get error from hooks (e.g. useCameraRoll and useGeolocation)

### ISSUE THREAD

**Issue by AleksandrChernyavenko** [react-native-community/react-native-hooks#7]
In current implementation we just ignore errors. In some cases we need access to error.
I guess we need add error in hooks response to avoid breaking changes later. 
What do you think about it ?

Example:
```
import { useGeolocation } from 'react-native-hooks'

const [position, stopObserving, setRNConfiguration, error] = useGeolocation()

console.log('latitude: ', position.coords.latitude)

console.log('error: ', error)
```

**Comment by melihberberolu** [comment]
You have a point! If React version support hooks and we can add error state in this hook.
Same time you can follow this post https://github.com/facebook/react-native/issues/21967#issuecomment-434113687 
then you can check all hooks and contribute hooks. But you can't use debug mode for hooks. @AleksandrChernyavenko

**Comment by guhungry** [comment]
Since geolocation was extracted from react native core. The geolocation hooks should be moved to https://github.com/react-native-community/react-native-geolocation

**Comment by pvinis** [comment]
We don't have `useGeolocation` anymore, so we can close this issue. Thanks!
